#!/usr/bin/env python3

import time
import pyfiglet
import shutil
import sys

def get_time_limit():
    if len(sys.argv) < 2:
        return 25
    
    if sys.argv[1] in ("-h", "--help"):
        print("Usage: pompy [minutes]")
        sys.exit(0)

    try:
        minutes = int(sys.argv[1])
        if minutes <= 0:
            raise ValueError
        return minutes

    except ValueError:
        print("Error: invalid minute(s) value")
        sys.exit(1)

def clear_screen():
    print("\033[2J\033[H", end="")

def print_centered(text):
    terminal_width = shutil.get_terminal_size().columns

    lines = text.splitlines()

    for line in lines:
        print(line.center(terminal_width))

def greet():
   input("Press ENTER to begin")
   clear_screen()
   pomodoro()

def pomodoro():
    time_limit = get_time_limit()
    total_seconds = time_limit * 60

    try:
        while total_seconds > 0:
            clear_screen()

            minutes = total_seconds // 60
            seconds = total_seconds % 60

            counter = f"{minutes:02d} : {seconds:02d}"
            art = pyfiglet.figlet_format(counter, font="big")
            print_centered(art)

            time.sleep(1)
            total_seconds -= 1

        print("\nTime's up!")

    except KeyboardInterrupt:
        clear_screen()
        print("\n\nPomodoro interrupted. Take a breath.")
        
if __name__ == "__main__":
    greet()

